services:
  - type: web
    name: mindsnap-agent-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /
    autoDeploy: true 